config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :items
  end

  root :to => 'users#index'
  resources :sessions
  resources :users

  get '/login' , to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: "users#new"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
	validates :name, presence: true, length: { maximum: 100 }
  

end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
  
  validates :phone_number,  format: { with: /\A[+][0-9][(][0-9]{3}[)][0-9]{3}[-][0-9]{2}[-][0-9]{2}\z/}, :allow_blank => true
  validates :name, length: { maximum: 20 }
  validates :surname, length: { maximum: 30 }
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
   
  include BaseControllerHelper

  layout 'admin'


  # before_action :signed_in_user
  # before_action :admin_user
  before_action :set_resource, only: [ :show, :edit, :update, :destroy]


  def index
  	plural_resource_name = "@#{resource_name.pluralize}"
    resources = resource_class.all
    instance_variable_set(plural_resource_name, resources)
  end

  def new
  	set_resource(resource_class.new)
  	get_resource
  end

  def create
    set_resource(resource_class.new(resource_params))

    if get_resource.save
      flash[:success] = "#{resource_name_capi} is created!"
      redirect_to send(admin_resourse_path)
    else
      flash.now[:danger] = "#{resource_name_capi} isn't create!" 
      render 'new'
    end

  end


  def update

       
    if get_resource.update_attributes(resource_params)
    	flash[:success] = "#{resource_name_capi} is success edit!"
      redirect_to send(admin_resourse_path)
    else
      flash.now[:danger] = "#{resource_name_capi} isn't edit!"
      render 'edit'
    end



  end

  def destroy
    get_resource.destroy
    flash[:success] = "#{resource_name_capi} is deleted!"
    redirect_to send(admin_resourse_path)
  end
  
  private 
    # return String
    def resource_name_capi
    	 resource_name.capitalize
    end
      
    # return String
    def admin_resourse_path
    	'admin_' + resource_name.pluralize + '_path'
    end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::BaseController

	private 
    def item_params
      params.require(:item).permit(:name, :description, :price,
                                   :image, :user_id, :shop_id, :category_id )
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
     @user = login( params[:session][:email], params[:session][:password],params[:session][:remember_me])
     if @user
      redirect_back_or_to(root_path)
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_back_or_to(root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  #root_path
  def index
  	
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Success singup!"
      redirect_to root_url

    else
      render 'new'
    end
  end



  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_controller_helper.rb
  module BaseControllerHelper
    

    # Returns the resource from the created instance variable
    # @return [Object]
    def get_resource
      instance_variable_get("@#{resource_name}")
    end


    # The resource class based on the controller
    # @return [Class]
    def resource_class
      @resource_class ||= resource_name.classify.constantize
    end

    # The singular name for the resource class based on the controller
    # @return [String]
    def resource_name
      @resource_name ||= self.controller_name.singularize
    end

    # Only allow a trusted parameter "white list" through.
    # If a single resource is loaded for #create or #update,
    # then the controller for the resource must implement
    # the method "#{resource_name}_params" to limit permitted
    # parameters for the individual model.
    def resource_params
      @resource_params ||= self.send("#{resource_name}_params")
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_resource(resource = nil)
      resource ||= resource_class.find(params[:id])
      instance_variable_set("@#{resource_name}", resource)
    end



  end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/items/edit.html.slim
div class="row row_form"
  h2 Редактирование товара
  = simple_form_for([:admin, @item]) do |f|

    = render partial: 'shared/form_item', locals: { f:f }

    = f.submit "Сохранить", class:  "btn btn-large btn-success" 

app/views/admin/items/index.html.slim
h2 class="sub-header" Товары

br
= link_to "Новый товар", new_admin_item_path, :class => "btn btn-large btn-primary" 

div class="table-responsive"
  table class="table table-striped" 
    thead
      tr
        th Name
        th Description
        th Price
        th Image
        th User_id
        th Shop_id
        th Category_id
        th Created_at
        th Updated_at
        th Edit/Destroy
    tbody
      - @items.each do |i|
        tr 
        td = i.name
        td = i.description
        td = i.price
        td = i.image
        td = i.user_id
        td = i.shop_id
        td = i.category_id
        td = i.created_at
        td = i.updated_at
        td = link_to('Edit', edit_admin_item_path(i.id))+'/'+link_to('Delete', admin_item_path(i.id), method: :delete,  data: { confirm: "Are you sure?"})

app/views/admin/items/new.html.slim
div class="row row_form"
  h2 Создание товара
  = simple_form_for([:admin, @item]) do |f|

    = render partial: 'shared/form_item',  locals: { f:f}

    = f.submit "Создать", class: "btn btn-large btn-success" 

app/views/layouts/admin.html.slim
doctype html
html
  head
    title Shop
    = csrf_meta_tags 
    = action_cable_meta_tag 

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' 
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' 
  

  body
    
    div class="row"
      div class="col-sm-3 col-md-2 sidebar"
        ul class="nav nav-sidebar"
          li class="active" 
            = link_to 'Товары',    admin_items_path 
      div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main"
        - flash.each do |key,value|
          div class="alert alert-#{key}"
             = value
        = yield 

app/views/layouts/application.html.slim
doctype html
html
  head
    title Shop
    = csrf_meta_tags 
    = action_cable_meta_tag 

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' 
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' 
  

  body
    - flash.each do |key,value|
      div class="alert alert-#{key}"
        = value


          
          


    -if current_user 
      =link_to "Log out", logout_path , method: :delete
    -else 
      =link_to("Sign up", signup_path) + '|' +  link_to("Log in", login_path)
      

    = yield


     

app/views/shared/_form_item.html.slim
= f.input :name        , label: 'Название'
= f.input :description , label: 'Описание'
= f.input :price       , label: 'Цена'
= f.input :image       , label: 'Изображение'
= f.input :user_id     , label: 'Создатель'
= f.input :shop_id     , label: 'Магазин'
= f.input :category_id , label: 'Категория'

app/views/users/index.html.slim
h1 Root path 

app/views/users/new.html.slim
div class="row row_form"
  h2 Sign up
  = simple_form_for(@user) do |f|
    = f.input :email
    = f.input :password
    = f.input :password_confirmation
    = f.submit "Create my account", class: "btn btn-large btn-success" 